# Generated by Django 4.2 on 2023-05-31 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no named', max_length=100, verbose_name='担当者')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='商品名')),
                ('money', models.IntegerField(default=0, verbose_name='金額')),
                ('size', models.IntegerField(default=0, verbose_name='大きさ')),
                ('quantity', models.IntegerField(default=0, verbose_name='個数')),
                ('color', models.CharField(default='', max_length=10, verbose_name='色')),
                ('date', models.CharField(default='', max_length=20, verbose_name='日付')),
                ('sold', models.CharField(default='', max_length=10, verbose_name='売り切れ')),
                ('note', models.CharField(blank=True, default='', max_length=10, verbose_name='備考')),
                ('manager_check', models.BooleanField(default=False, verbose_name='担当者チェック')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.user', verbose_name='担当者')),
            ],
        ),
    ]
