# Generated by Django 4.2 on 2023-05-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='商品名')),
                ('money', models.IntegerField(verbose_name='金額')),
                ('note', models.CharField(blank=True, default='', max_length=10, verbose_name='備考')),
            ],
        ),
    ]
