# Generated by Django 4.2 on 2023-05-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='color',
            field=models.CharField(default='', max_length=10, verbose_name='色'),
        ),
        migrations.AddField(
            model_name='shop',
            name='date',
            field=models.CharField(default='', max_length=20, verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='shop',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='個数'),
        ),
        migrations.AddField(
            model_name='shop',
            name='size',
            field=models.IntegerField(default=0, verbose_name='大きさ'),
        ),
        migrations.AddField(
            model_name='shop',
            name='sold',
            field=models.CharField(default='', max_length=10, verbose_name='売り切れ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='money',
            field=models.IntegerField(default=0, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='商品名'),
        ),
    ]
